#!/bin/bash

dir=${PWD##*/}
cd ..
month=${PWD##*/}
cd $dir

cap_files='pcaps/*.pcap'

for file in $cap_files
do
        echo $file >> input
done

rwp2yaf2silk --yaf-args=--caplist --in=input --out=silk_${month}_${dir}.rw

rm input
